[package]
name = "stremio-shell-ng"
version = "0.1.0"
edition = "2018"

[dependencies]
once_cell = "1.3.1"
native-windows-gui = { version = "1.0.4", features = ["high-dpi", "notice"] }
native-windows-derive = "1.0.3"
winapi = { version = "0.3.9", features = [
    "libloaderapi", "handleapi", "wincon", "winuser"
] }
webview2 = "0.1.0"
webview2-sys = "0.1.0-beta.1"
mpv = "0.2.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"

[build-dependencies]
embed-resource = "1.3"